#
# Copyright (C) 2018 Jo-Philipp Wich <jo@mein.io>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=OWM App
LUCI_DEPENDS:=+luci-lib-json +olsrd-mod-jsoninfo +luci-lib-ip +luci-lib-httpclient

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
